name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

env:
  # TODO: Change variable to your image's name.
  BITCOIN_IMAGE_NAME: electrs
  LIQUID_IMAGE_NAME: electrs-liquid
  COMMIT: 253040e346664976c12e6c214ee2858a4dad2e06

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  bitcoin:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run:  >-
          docker buildx build --push 
          --file ./$COMMIT/Dockerfile 
          --tag ghcr.io/vulpemventures/$BITCOIN_IMAGE_NAME:latest 
          --tag ghcr.io/vulpemventures/$BITCOIN_IMAGE_NAME:$COMMIT 
          --platform linux/arm64,linux/amd64 .

  liquid:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run:  >-
          docker buildx build --push 
          --file ./$COMMIT/Dockerfile.liquid 
          --tag ghcr.io/vulpemventures/$LIQUID_IMAGE_NAME:latest 
          --tag ghcr.io/vulpemventures/$LIQUID_IMAGE_NAME:$COMMIT 
          --platform linux/arm64,linux/amd64 .
